version: '3'

services:
  netmapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netmapper
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - TZ=UTC
      - DATABASE_PATH=/app/data/device_mappings.db
      - CREDENTIALS_PATH=/app/data/credentials.json
      - CONFIG_PATH=/app/config/netmapper.json
      - USE_ENCRYPTION=${USE_ENCRYPTION:-false}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
    restart: unless-stopped
    command: --config /app/config/netmapper.json --daemon --interval 3600

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: netmapper-api
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "5000:5000"
    environment:
      - TZ=UTC
      - DATABASE_PATH=/app/data/device_mappings.db
      - CREDENTIALS_PATH=/app/data/credentials.json
      - CONFIG_PATH=/app/config/netmapper.json
      - USE_ENCRYPTION=${USE_ENCRYPTION:-false}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
    depends_on:
      - netmapper
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: netmapper-web
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
